# Generated by Django 5.2.3 on 2025-06-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
